apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: wili
data:
  NODE_ENV: "production"
  PUBLIC_API_BASE_URL: "https://api.wili.me"
  PUBLIC_AUTH_API_BASE_URL: "https://api.wili.me"
  PUBLIC_USER_API_BASE_URL: "https://api.wili.me"
  PUBLIC_WISHLIST_API_BASE_URL: "https://api.wili.me/wishlists"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: wili
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: cr.yandex/REGISTRY_ID_PLACEHOLDER/frontend:IMAGE_TAG_PLACEHOLDER
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: frontend-config
              key: NODE_ENV
        - name: PUBLIC_API_BASE_URL
          valueFrom:
            configMapKeyRef:
              name: frontend-config
              key: PUBLIC_API_BASE_URL
        - name: PUBLIC_AUTH_API_BASE_URL
          valueFrom:
            configMapKeyRef:
              name: frontend-config
              key: PUBLIC_AUTH_API_BASE_URL
        - name: PUBLIC_USER_API_BASE_URL
          valueFrom:
            configMapKeyRef:
              name: frontend-config
              key: PUBLIC_USER_API_BASE_URL
        - name: PUBLIC_WISHLIST_API_BASE_URL
          valueFrom:
            configMapKeyRef:
              name: frontend-config
              key: PUBLIC_WISHLIST_API_BASE_URL
        # VITE_YANDEX_CLIENT_ID is now built into the image at build time
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: wili
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 3000
  type: ClusterIP