apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
  namespace: wili
data:
  PORT: "8080"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "userdb"
  DB_USER: "postgres"
  DATABASE_URL: "postgres://postgres:postgres@postgres-service:5432/userdb?sslmode=disable"

---
apiVersion: v1
kind: Secret
metadata:
  name: user-service-secret
  namespace: wili
type: Opaque
data:
  DB_PASSWORD: DB_PASSWORD_PLACEHOLDER # Will be replaced by GitHub secrets
  JWT_SECRET: JWT_SECRET_PLACEHOLDER # Will be replaced by GitHub secrets

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: wili
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: cr.yandex/REGISTRY_ID_PLACEHOLDER/user-service:IMAGE_TAG_PLACEHOLDER
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: user-service-config
              key: PORT
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: user-service-config
              key: DATABASE_URL
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: user-service-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: user-service-config
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: user-service-config
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: user-service-config
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: user-service-secret
              key: DB_PASSWORD
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: user-service-secret
              key: JWT_SECRET
        - name: YANDEX_CLIENT_ID
          valueFrom:
            configMapKeyRef:
              name: yandex-auth-config
              key: YANDEX_CLIENT_ID
        - name: YANDEX_CLIENT_SECRET
          valueFrom:
            configMapKeyRef:
              name: yandex-auth-config
              key: YANDEX_CLIENT_SECRET
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: wili
spec:
  selector:
    app: user-service
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP