apiVersion: v1
kind: ConfigMap
metadata:
  name: wishlist-service-config
  namespace: wili
data:
  PORT: "8080"
  MONGO_HOST: "mongodb-service"
  MONGO_PORT: "27017"
  MONGO_DATABASE: "wishlistdb"
  USER_SERVICE_URL: "http://user-service"

---
apiVersion: v1
kind: Secret
metadata:
  name: wishlist-service-secret
  namespace: wili
type: Opaque
data:
  MONGO_USERNAME: YWRtaW4= # base64 encoded "admin" - should match mongodb secret
  MONGO_PASSWORD: cGFzc3dvcmQ= # base64 encoded "password" - should match mongodb secret

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wishlist-service
  namespace: wili
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wishlist-service
  template:
    metadata:
      labels:
        app: wishlist-service
    spec:
      containers:
      - name: wishlist-service
        image: cr.yandex/YOUR_REGISTRY_ID/wishlist-service:latest
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: wishlist-service-config
              key: PORT
        - name: MONGO_HOST
          valueFrom:
            configMapKeyRef:
              name: wishlist-service-config
              key: MONGO_HOST
        - name: MONGO_PORT
          valueFrom:
            configMapKeyRef:
              name: wishlist-service-config
              key: MONGO_PORT
        - name: MONGO_DATABASE
          valueFrom:
            configMapKeyRef:
              name: wishlist-service-config
              key: MONGO_DATABASE
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: wishlist-service-secret
              key: MONGO_USERNAME
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wishlist-service-secret
              key: MONGO_PASSWORD
        - name: USER_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: wishlist-service-config
              key: USER_SERVICE_URL
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: wishlist-service
  namespace: wili
spec:
  selector:
    app: wishlist-service
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP